begin;

do $$
declare
  sequence_name text;
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'classes'
      and column_name = 'class_id'
      and is_identity = 'NO'
      and column_default is null
  ) then
    alter table classes
    alter column class_id add generated by default as identity;
  end if;

  select pg_get_serial_sequence('classes', 'class_id') into sequence_name;
  if sequence_name is not null then
    execute format(
      'select setval(%L, (select coalesce(max(class_id), 0) + 1 from classes), false)',
      sequence_name
    );
  end if;
end $$;

commit;
